[package]
name = "leptos-icons"
version = "0.1.0"
edition = "2021"

# build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.2.1", default-features = false }
url = { version = "2.3.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
rayon = "1.7.0"
anyhow = "1.0"
heck = "0.4.1"
xml-rs = "0.8.4"
indicatif = { version = "0.17.3", features = ["rayon"]}

# [build-dependencies]
# url = { version = "2.3.1", features = ["serde"] }
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0.93"
# rayon = "1.7.0"
# anyhow = "1.0"
# convert_case = "0.6.0"
# svgcleaner = "0.9.5"
