[package]
name = "leptos-icons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = {version = "2.3.1", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.93"
rayon = "1.7.0"
anyhow = "1.0"
include_dir = "0.7.3"
case = "1.0.0"
