[tasks.css-watch]
script = "npx tailwindcss -i input.css -o output.css --watch"

[tasks.css-build]
script = "npx tailwindcss -i input.css -o output.css"

[tasks.trunk]
command = "trunk"
args = ["serve", "--open"]

[tasks.run]
run_task = { name = ["css-watch", "trunk"], parallel = true }
