jobs: 
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nightly with wasm
        uses: ThexXTURBOXx/toolchain@master
        with:
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly
      - name: Build website
        run: "cd icon_index && trunk build"
  
  deploy_site:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Add a dependency to the build job
    needs: build_site
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      id-token: write   # to verify the deployment originates from an appropriate source
      pages: write      # to deploy to Pages

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs/'
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2


name: Build & Deploy Site
on:
  pull_request:
    types:
      - closed
