name: Publish Crate

on:
  workflow_dispatch:

jobs:
  publish_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nightly with wasm
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly
      - name: list all icondata directories
        #  env:
        #  CRATES_IO_TOKEN: ${{ secrets.CARGO_LOGIN }}
        run: ls -d icondata_!(core)
