name: Publish Crate

on:
  workflow_dispatch:

jobs:
  publish_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nightly with wasm
        uses: ThexXTURBOXx/toolchain@master
        with:
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly
      - name: Publish all Crates
        env:
          CRATES_IO_TOKEN: ${{ secrets.CARGO_LOGIN }}
        run: find . -maxdepth 1 -type d -name 'icondata*' ! -name 'icondata_core' -print0 | xargs -0 -I {} sh -c 'cd {} && cargo publish --token $CRATES_IO_TOKEN'
